"""initial_novel_schema

Revision ID: 0d14ec460ddd
Revises: 
Create Date: 2026-10-06 10:17:42.981688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d14ec460ddd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_translation_providers_id'), 'translation_providers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('novels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_domain', sa.String(length=255), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novels_id'), 'novels', ['id'], unique=False)
    op.create_index(op.f('ix_novels_title'), 'novels', ['title'], unique=False)
    op.create_index(op.f('ix_novels_url'), 'novels', ['url'], unique=True)
    op.create_index(op.f('ix_novels_user_id'), 'novels', ['user_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_chapter_number'), 'chapters', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    op.create_index(op.f('ix_chapters_novel_id'), 'chapters', ['novel_id'], unique=False)
    op.create_index(op.f('ix_chapters_status'), 'chapters', ['status'], unique=False)
    op.create_table('translation_glossary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('source_term', sa.String(length=255), nullable=False),
    sa.Column('translated_term', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_glossary_id'), 'translation_glossary', ['id'], unique=False)
    op.create_index(op.f('ix_translation_glossary_novel_id'), 'translation_glossary', ['novel_id'], unique=False)
    op.create_table('chapter_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('paragraph_count', sa.Integer(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_contents_chapter_id'), 'chapter_contents', ['chapter_id'], unique=True)
    op.create_index(op.f('ix_chapter_contents_id'), 'chapter_contents', ['id'], unique=False)
    op.create_index(op.f('ix_chapter_contents_source_hash'), 'chapter_contents', ['source_hash'], unique=False)
    op.create_table('crawl_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('scraper_used', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_logs_chapter_id'), 'crawl_logs', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_crawl_logs_id'), 'crawl_logs', ['id'], unique=False)
    op.create_index(op.f('ix_crawl_logs_novel_id'), 'crawl_logs', ['novel_id'], unique=False)
    op.create_table('translation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_chunk', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_jobs_chapter_id'), 'translation_jobs', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_translation_jobs_id'), 'translation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_translation_jobs_novel_id'), 'translation_jobs', ['novel_id'], unique=False)
    op.create_index(op.f('ix_translation_jobs_status'), 'translation_jobs', ['status'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('translated_title', sa.String(length=500), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_chapter_id'), 'translations', ['chapter_id'], unique=True)
    op.create_index(op.f('ix_translations_id'), 'translations', ['id'], unique=False)
    op.create_index(op.f('ix_translations_source_hash'), 'translations', ['source_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_source_hash'), table_name='translations')
    op.drop_index(op.f('ix_translations_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_chapter_id'), table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_translation_jobs_status'), table_name='translation_jobs')
    op.drop_index(op.f('ix_translation_jobs_novel_id'), table_name='translation_jobs')
    op.drop_index(op.f('ix_translation_jobs_id'), table_name='translation_jobs')
    op.drop_index(op.f('ix_translation_jobs_chapter_id'), table_name='translation_jobs')
    op.drop_table('translation_jobs')
    op.drop_index(op.f('ix_crawl_logs_novel_id'), table_name='crawl_logs')
    op.drop_index(op.f('ix_crawl_logs_id'), table_name='crawl_logs')
    op.drop_index(op.f('ix_crawl_logs_chapter_id'), table_name='crawl_logs')
    op.drop_table('crawl_logs')
    op.drop_index(op.f('ix_chapter_contents_source_hash'), table_name='chapter_contents')
    op.drop_index(op.f('ix_chapter_contents_id'), table_name='chapter_contents')
    op.drop_index(op.f('ix_chapter_contents_chapter_id'), table_name='chapter_contents')
    op.drop_table('chapter_contents')
    op.drop_index(op.f('ix_translation_glossary_novel_id'), table_name='translation_glossary')
    op.drop_index(op.f('ix_translation_glossary_id'), table_name='translation_glossary')
    op.drop_table('translation_glossary')
    op.drop_index(op.f('ix_chapters_status'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_novel_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_chapter_number'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_novels_user_id'), table_name='novels')
    op.drop_index(op.f('ix_novels_url'), table_name='novels')
    op.drop_index(op.f('ix_novels_title'), table_name='novels')
    op.drop_index(op.f('ix_novels_id'), table_name='novels')
    op.drop_table('novels')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_translation_providers_id'), table_name='translation_providers')
    op.drop_table('translation_providers')
    # ### end Alembic commands ###
